Repository hazelcast/hazelcast-jet-code-samples, pull requests merged in 2019-02, with the labels that each got.

#169 Fix gRPC java9 issue
  enrichment/pom.xml
Labels: bug

#175 Compilation fixes
  core-api/sliding-windows-core-api/src/main/java/StockExchangeSingleStage.java
  tf-idf/src/main/java/TfIdf.java
Labels: enhancement

#167 Do not reuse same JobConfig object
  job-management/src/main/java/JobUpdate.java
Labels: bug

#173 Replace submit.sh usages with CLI
  integration/kubernetes/hazelcast-jet-config.yaml
  integration/kubernetes/pom.xml
  integration/kubernetes/rolling-aggregation.yaml
  integration/kubernetes/src/main/java/TradingVolume.java
  integration/kubernetes/src/main/resources/log4j.properties
Labels: enhancement

#179 Set imdg version to 3.12-BETA-1
  pom.xml
Labels: enhancement

#183 Follow changes in core
  enrichment/src/main/java/Enrichment.java
Labels: follow changes in deps

#184 Follow changes in core
  core-api/enrichment-core-api/src/main/java/HashJoinP.java
  core-api/enrichment-core-api/src/main/java/HashMapEnrichment.java
  core-api/sliding-windows-core-api/src/main/java/StockExchangeCoreApi.java
  core-api/sliding-windows-core-api/src/main/java/StockExchangeSingleStage.java
  core-api/tf-idf-core-api/src/main/java/TfIdfCoreApi.java
  core-api/wordcount-core-api/src/main/java/WordCountCoreApi.java
  core-api/wordcount-core-api/src/main/java/benchmark/WordCountSingleNode.java
  enrichment/src/main/java/Enrichment.java
  file-io/src/main/java/AccessLogAnalyzer.java
  hadoop/src/main/java/HadoopWordCount.java
  hazelcast-connectors/src/main/java/MapSourceAndSinks.java
  integration/kubernetes/src/main/java/TradingVolume.java
  integration/pcf/src/main/java/PipelineBuilder.java
  rolling-aggregation/src/main/java/TradingVolume.java
  sliding-windows/src/main/java/StockExchange.java
  sliding-windows/src/main/java/TopNStocks.java
  sockets/src/main/java/StreamTextSocket.java
  sockets/src/main/java/WriteTextSocket.java
  tf-idf/src/main/java/TfIdf.java
  wordcount/src/main/java/WordCount.java
Labels: follow changes in deps

#185 Update Hazelcast Jet version to 3.0-SNAPSHOT
  co-group/pom.xml
  core-api/enrichment-core-api/pom.xml
  core-api/map-dump/pom.xml
  core-api/pom.xml
  core-api/prime-finder/pom.xml
  core-api/sliding-windows-core-api/pom.xml
  core-api/tf-idf-core-api/pom.xml
  core-api/wordcount-core-api/pom.xml
  early-window-results/pom.xml
  enrichment/pom.xml
  enterprise/pom.xml
  event-journal/pom.xml
  fault-tolerance/pom.xml
  file-io/pom.xml
  hadoop/pom.xml
  hazelcast-connectors/pom.xml
  integration/docker-compose/pom.xml
  integration/kubernetes/pom.xml
  integration/pcf/pom.xml
  integration/pom.xml
  integration/spring/pom.xml
  integration/spring/src/main/resources/application-context-with-schema.xml
  jdbc/pom.xml
  jms/pom.xml
  job-management/pom.xml
  kafka/pom.xml
  pom.xml
  rolling-aggregation/pom.xml
  session-windows/pom.xml
  sink-builder/pom.xml
  sliding-windows/pom.xml
  sockets/pom.xml
  source-builder/pom.xml
  tensorflow/pom.xml
  tf-idf/pom.xml
  wordcount/pom.xml
Labels: follow changes in deps
